- pmd/rulesets/backend-java-ruleset.xml
excluded rule [AvoidObjectMapperAsField](https://github.com/jborgers/PMD-jPinpoint-rules/blob/d79a452249486c59a0a72e8d42c4ffe7c0e64f35/docs/JavaCodePerformance.md\#iuojar02) 
as it doesn't work as describe in documentation 
```java
class ExceptionCase {
private static final ObjectMapper staticObjectMapper = new ObjectMapper(); //accepted by AvoidObjectMapperAsField
private final ObjectMapper mapperField = new ObjectMapper(); //bad by AvoidObjectMapperAsField
public UserProfileDto getUserProfileDto(UserProfile userProfile) {
return staticObjectMapper.convertValue(userProfile, UserProfileDto.class);
}
}
```
but we get an error even though we don't set conf after initialisation so we should be good with only `AvoidModifyingObjectMapper`
> exclude AvoidObjectMapperAsField

- pmd/rulesets/backend-java-ruleset.xml
This way, variable like ID will not raise warnings
> make short variable exclusion regex case-insensitive

- pmd/rulesets/backend-java-ruleset.xml
deactivate rule UselessParentheses because we have many false positive as we use parentheses to clarify boolean expressions. 
We will reactivate it when pmd 7 will be released as it will be possible to set rule to allow parentheses when they are used for clarification. see : https://github.com/pmd/pmd/issues/1918
> deactivate UselessParentheses

- pmd/rulesets/backend-java-ruleset.xml
Too many false positive, as rule doesn't take object creation with interator derived objects into consideration
> deactivate AvoidInstantiatingObjectsInLoops

- pmd/rulesets/backend-java-ruleset.xml
As we are introducing test apis some of the classes involved start with Test.  these classes shouldn't be considered as Test classes. None of our test classes start with Test so this shouldn't have been in the regex in the first place
> exclude class starting with Test from test classes

- pmd/rulesets/arch4u-ruleset-tweaked.xml
- pmd/rulesets/backend-java-ruleset.xml
fix https://github.com/libon/backend-system-backlog/issues/30
see https://github.com/libon/parent/pull/574
> Thanks to https://github.com/apache/maven-pmd-plugin/pull/141#issuecomment-1886820989 we don't need to use snapshot version of maven-pmd-plugin but only pmd release candidate 7.0.0-rc4
> The compatibility module only work on built in rules so I have removed arch4u rules but I have kept the rules that he had tweaked to reduce false positive occurrences when using framework like Spring. see [libon/backend-code-rulesets@tweaks-for-pmd-7.0.0/pmd/rulesets/arch4u-ruleset-tweaked.xml](https://github.com/libon/backend-code-rulesets/blob/tweaks-for-pmd-7.0.0/pmd/rulesets/arch4u-ruleset-tweaked.xml?rgh-link-date=2024-01-11T16%3A00%3A00Z)
> We loose …
> tweaks for pmd 7.0.0

- pmd/rulesets/backend-java-ruleset.xml
When we are overriding a method, its not our fault if we have too many parameters
> ignore ExcessiveParameterList when it's an overriding method

- pmd/rulesets/backend-java-ruleset.xml
Lower CyclomaticComplexity warning level, because its a good thing to be aware but it shouldn't be that high.
increased method minimal complexity to 20
> [!TIP]
> pmd priority 1 is the highest and 5 the lowest
> lower CyclomaticComplexity warning level

- pmd/rulesets/backend-java-ruleset.xml
Test class regex shouldn't match classes names like `TestHelper` since they are not test classes.
> improve test class name regex

- pmd/rulesets/backend-java-ruleset.xml
tweak ConstructorCallsOverridableMethod to ignore warning when class extend ResourceConfig
> fix regex and restrict AvoidFieldNameMatchingMethodName to classes that contains get/set + tweak ConstructorCallsOverridableMethod

- pmd/rulesets/backend-java-ruleset.xml
rest of tweaks is taken from `<rule ref="https://raw.githubusercontent.com/libon/backend-code-rulesets/tweaks-for-pmd-7.0.0/pmd/rulesets/arch4u-ruleset-tweaked.xml">` since we have excluded it to tweak it
> consider private methods with `@AssertTrue` used

- pmd/rulesets/backend-java-ruleset.xml
if final is put on an entity setter we get an exception from hibernate 
> [main] WARN o.h.m.i.EntityRepresentationStrategyPojoStandard [correlationid=] - HHH000305: Could not create proxy factory
> exclude entities from ConstructorCallsOverridableMethod

- pmd/rulesets/backend-java-ruleset.xml
When we annotate data class with @UtilityClass it means that we thought about it and it is relevant to have this data class
> exclude UtilityClass from DataClass

- pmd/rulesets/backend-java-ruleset.xml
Since we use pattern matching this rule is no longer relevant
> exclude SwitchDensity rule

- pmd/rulesets/backend-java-ruleset.xml
rule was not from arch4u-ruleset-tweaked
```
[WARNING] Warning at /home/jenkins/agent/workspace/Libon_backend-dps_PR-79@tmp/codeAnalysis.tmp16542854950258801439/domain-objects/target/pmd/rulesets/001-backend-java-ruleset.xml:66:9
10:22:47   64|         <exclude name="ShortMethodName"/>
10:22:47   65|         <exclude name="ShortVariable"/>
10:22:47   66|         <exclude name="SwitchDensityRule"/>
10:22:47               ^^^^^^^^ Exclude pattern 'SwitchDensityRule' did not match any rule in ruleset 'https://raw.githubusercontent.com/libon/backend-code-rulesets/tweaks-for-pmd-7.0.0/pmd/rulesets/arch4u-ruleset-tweaked.xml'
10:22:47  
10:22:47   67|         
10:22:47   68|         <exclude name="SwitchStmtsShouldHaveDefault"/>
```
> exclude SwitchDensity rule from jpinpoint

- pmd/rulesets/backend-java-ruleset.xml
rule is also not found in SwitchDensityRule
```
[WARNING] Warning at /home/jenkins/agent/workspace/Libon_backend-dps_PR-79@tmp/codeAnalysis.tmp4732337927714008743/providers/sochitel/target/pmd/rulesets/001-backend-java-ruleset.xml:25:9
10:48:22   23|         To reactivate in pmd 7.0.0 as each node will have a getRoot method which will return package name -->
10:48:22   24|         <exclude name="NonComparableMapKeys"/>
10:48:22   25|         <exclude name="SwitchDensityRule"/>
10:48:22               ^^^^^^^^ Exclude pattern 'SwitchDensityRule' did not match any rule in ruleset 'https://raw.githubusercontent.com/jborgers/PMD-jPinpoint-rules/44375f0e771757ad0798d2e6947d3aa37ef69d3d/rulesets/java/jpinpoint-rules.xml'
10:48:22  
10:48:22   26|     </rule>
10:48:22   27|     <rule …
```
> remove SwitchDensityRule exclusion

- pmd/rulesets/backend-java-ruleset.xml
When we have `@Transactional` on class level we tend not to check if newly added methods really need to be in a transaction. this new rule will force use to put the annotation on a method level thus ensuring that it is added only when needed
> add custom rule AvoidTransactionalOnClassLevel

- pmd/rulesets/backend-java-ruleset.xml
When an enum has a lot of entries we get this warning, recommending to split into multiple classes but this would change the behavior when its used
> suppress ExcessivePublicCount on Enums

- pmd/rulesets/backend-java-ruleset.xml
we only want to have warn `MoreThanOneLogger` when multiple class based logger are defined in the class and not when other logger are specific loggers (i.e. based on custom strings)
```java
// Valid
private static final Logger LOGGER = LoggerFactory.getLogger(CallAuthorizationService.class);
private static final Logger NUMBER_PATTERN_LOGGER = LoggerFactory.getLogger("number-pattern-logger");
private static final Logger DIFF_LOGGER = LoggerFactory.getLogger("diff-logger");
```
```java
// Not valid
private static final Logger LOGGER = LoggerFactory.getLogger(CallAuthorizationService.class);
private static final Logger NUMBER_PATTERN_LOGGER = LoggerFactory.getLogger(NumberMatcher.class);
private static final Logger DIFF_LOGGER = LoggerFactory.getLogger("diff-logger");
```
> suppress MoreThanOneLogger on custom string loggers

- pmd/rulesets/backend-java-ruleset.xml
When we have private methods in our classes it is most of the time to clarify an exposed method in the class so lets exclude them from count because it would be less readable/maintainable to have them else where
> ignore private methods for TooManyMethods

- pmd/rulesets/backend-java-ruleset.xml
I have added this rule because I has occured that sometimes test are still valid even though the reason behind the `BadRequestException` is not the one expected by the test. This rule should push us to be more precise on the exception reason on our tests
> add rule HttpClientExceptionAssertionShouldHaveMessageValidation
